baseURL = "https://boring-jepsen-70e6cc.netlify.app/"
languageCode = "en-us"
title = "Amplified Together"
theme = "amplified-together"

[taxonomies]
    theme = "themes"
    discipline = "disciplines"